sudo: required

services:
    - docker

before_install:
    - docker pull ajudgeteam/ajudge:test

language: python
python:
  - "3.6"

cache: pip

# command to run tests
script: python test.py

notifications:
  slack: ccw-geeks:J7F1Lq4jHyoP6vP33SwDWFKf
